name: 'Docker build and push'
description: 'Build and push a Docker image to Azure Container Registry using Service Principal'

inputs:
  azure-registry:
    description: 'Azure Container Registry'
    required: true
  build-args:
    description: 'A list of arguments to pass to the build'
    required: false
    default: ''
  client-id:
    description: 'Azure Service Principal Client ID'
    required: false
    default: ''
  context:
    description: 'The build context to use'
    required: false
    default: '.'
  dockerfile:
    description: 'The Dockerfile to use'
    required: false
    default: 'Dockerfile'
  image-name:
    description: 'The name of the image to build'
    required: false
    default: 'app'
  platform:
    description: 'The platform to build the image for'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Whether to push the image to the registry'
    required: false
    default: 'false'
  subscription-id:
    description: 'Azure Subscription ID'
    required: false
    default: ''
  tag:
    description: 'A tag for the image'
    required: false
    default: 'latest'
  tenant-id:
    description: 'Azure Service Principal Tenant ID'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up env for ACR domain
      shell: bash
      run: |
        REGISTRY_NAME="${{ inputs.azure-registry }}"
        echo REGISTRY_NAME="${REGISTRY_NAME%.azurecr.io}" >> $GITHUB_ENV

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        subscription-id: ${{ inputs.subscription-id }}
        tenant-id: ${{ inputs.tenant-id }}

    - name: Log in to ACR
      shell: bash
      run: |
        az acr login --name ${{env.REGISTRY_NAME}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        cache-from: type=registry,ref=${{env.REGISTRY_NAME}}.azurecr.io/${{ inputs.image-name }}:${{ inputs.tag }}
        cache-to: type=inline
        platforms: ${{ inputs.platform }}
        push: ${{ inputs.push }}
        tags: ${{env.REGISTRY_NAME}}.azurecr.io/${{ inputs.image-name }}:${{ inputs.tag }}
