providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  listeners:
    web:
      port: 8000
      namespacePolicy: All
      protocol: HTTP
    websecure:
      port: 8443
      namespacePolicy: All
      protocol: HTTPS
      mode: Terminate
      hostname: studgart.com
      certificateRefs:
        - name: studgart-com-tls

