name: 'Typescript build and test'
description: 'Build and test a Typescript project'

inputs:
  working-directory:
    description: 'Working directory'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: npm install
      shell: bash
      run: npm install
      working-directory: ${{ inputs.working-directory }}

    - name: npm run build
      shell: bash
      run: npm run build
      working-directory: ${{ inputs.working-directory }}
