name: "Develop"

on:
  push:
    branches:
      - develop
      - features/cicd

jobs:

  pre-workflow:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/rw-pre-workflow.yml

  frontend:
    permissions:
      contents: read
      id-token: write
    needs: pre-workflow
    if: ${{ needs.pre-workflow.outputs.frontend == 'true' }}
    uses: ./.github/workflows/rw-build-deploy.yml
    with:
      working-dir: frontend

  backend:
    permissions:
      contents: read
      id-token: write
    needs: pre-workflow
    if: ${{ needs.pre-workflow.outputs.backend == 'true' }}
    uses: ./.github/workflows/rw-build-deploy.yml
    with:
      working-dir: backend
