name: "Open PR into branch dev"

on:
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build-typescript-frontend:
    name: '[Frontend] Build TypeScript'
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        uses: ./.github/actions/build-typescript
        with:
          working-directory: frontend
          env-file-content: ${{ vars.FRONTEND_ENV }}
  build-docker-frontend:
    name: '[Frontend] Build Docker'
    needs: build-typescript-frontend
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        uses: ./.github/actions/build-docker
        with:
          # SERVICE PRINCIPAL
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          # IMAGE DETAILS
          azure-registry: 0g3fdXCei4iLQUet
          context: frontend
          dockerfile: frontend/Dockerfile
          image-name: frontend
  backend-build-typescript:
    name: '[Backend] Build TypeScript'
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        uses: ./.github/actions/build-typescript
        with:
          working-directory: backend
          env-file-content: ${{ vars.BACKEND_ENV }}
  backend-build-docker:
    name: '[Backend] Build Docker'
    needs: backend-build-typescript
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        uses: ./.github/actions/build-docker
        with:
          # SERVICE PRINCIPAL
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          # IMAGE DETAILS
          azure-registry: 0g3fdXCei4iLQUet
          context: backend
          dockerfile: backend/Dockerfile
          image-name: backend