name: "Build and Deploy"

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      PROJECT_VARIABLES:
        required: true
        type: string
    secrets:
      PROJECT_SECRETS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get Environment Variables from GitHub Variables
        run: |
          touch .env
          echo ${{ inputs.PROJECT_VARIABLES }} > .env
          echo ${{ secrets.PROJECT_SECRETS }} > .env
        working-directory: ${{ inputs.working-dir }}
      
      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working-dir }}
      
      - name: Build
        run: npm run build
        working-directory: ${{ inputs.working-dir }}

      - name: Check .env file
        run: cat .env
        working-directory: ${{ inputs.working-dir }}